# Generated by Django 3.2.7 on 2021-10-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsauthors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsAuthors',
        ),
    ]
